name: Tests

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop

jobs:
  run-tests:
    runs-on: ubuntu-latest
    environment: test
    permissions:
      checks: write
      contents: read
    strategy:
      matrix:
        node-version: [20.11.0]
    steps:
      - uses: actions/checkout@v2

      - uses: pnpm/action-setup@v2
        with:
          version: 8

      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - uses: nrwl/nx-set-shas@v4

      - name: Check code
        run: pnpm nx affected -t=lint --base=develop --head=HEAD --parallel

      - name: Run tests
        run: pnpm nx affected -t=test --base=develop --head=HEAD --parallel

      - name: Publish test report
        uses: paambaati/codeclimate-action@v5.0.0
        env:
          CC_TEST_REPORTER_ID: ${{ secrets.CODECLIMATE_REPO_TOKEN }}
        with:
          coverageCommand: pnpm coverage-merge
          coverageLocation: |
            ${{ github.workspace }}/coverage/lcov.info:lcov

      - name: Run Build
        run: pnpm nx affected -t=build --base=develop --head=HEAD --parallel
