name: Develop CI Pipeline

on:
  push:
    branches:
      - develop

permissions:
  actions: read
  contents: read

jobs:
  run-tests:
    runs-on: ubuntu-latest
    permissions:
      checks: write
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install
        uses: ./.github/workflows/templates/install

      - uses: nrwl/nx-set-shas@v4

      - name: Test & Build
        run: pnpm exec nx affected -t=lint,test,build,build-storybook --parallel --configuration=ci

      - name: Publish test report
        uses: paambaati/codeclimate-action@v5.0.0
        env:
          CC_TEST_REPORTER_ID: ${{ secrets.CODECLIMATE_REPO_TOKEN }}
        with:
          coverageCommand: pnpm run coverage-merge
          coverageLocation: |
            ${{ github.workspace }}/coverage/lcov.info:lcov
